title: Machine Learning for Health
description: Uniiversity of Toronto CS2541 Machine Learning for Health

url: http://CS2541-ML4H2019.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Project
   url: /Project
 - title: Schedule
   url: /schedule
 # - title: Contact
 #   url: /contact

social:
   github: CS2541-ML4H2019
   twitter: #twitter
   facebook: 
   email: #

google_analytics: "UA-58263416-1"
